name: Deploy en AWS Lightsail

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Conexion SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Despliegue en Lightsail
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.58.239.119 << 'EOF'
          # Verificar si el directorio existe
          if [ ! -d "/var/www/html" ]; then
            echo "/var/www/html no existe. Creando directorio."
            sudo mkdir -p /var/www/html
          fi

          # Cambiar permisos para el directorio /var/www/html
          sudo chown -R ubuntu:ubuntu /var/www/html

          cd /var/www/html

          # Eliminar archivos si es necesario
          # sudo rm -rf *

          # Si el repositorio ya está clonado, hacer pull
          if [ -d ".git" ]; then
              git pull origin main
          else
              git clone https://github.com/Practicas-PS/Nestjs-Api.git .
          fi
          EOF
